
#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 0.1.{build}.0
os: unstable
install: 
  - cinst -y pester

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps:
        $ProjectRoot = $ENV:APPVEYOR_BUILD_FOLDER
        Set-Location $ProjectRoot
        Import-Module Pester
        $res = Invoke-Pester -Path "$ProjectRoot\Tests" -OutputFormat NUnitXml -OutputFile "$ProjectRoot\TestResults.xml" -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "$ProjectRoot\TestResults.xml"))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
