
#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 0.1.{build}.0
install: 
  - cinst -y pester

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        # xDscResouceDesigner works against standard PowerShell modules path.
        # We need to make sure that root folder of LabBuilder is at the first place in $env:PSModulePath
        if (($env:PSModulePath.Split(';') | select -First 1) -ne $pwd) {
            $env:PSModulePath = "$pwd;$env:PSModulePath"
        }
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
